# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: temporal_parsing.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16temporal_parsing.proto\":\n\x16TemporalParsingRequest\x12\x11\n\tutterance\x18\x01 \x01(\t\x12\r\n\x05today\x18\x02 \x01(\t\"Q\n\x17TemporalParsingResponse\x12&\n\x06status\x18\x01 \x01(\x0e\x32\x16.TemporalParsingStatus\x12\x0e\n\x06result\x18\x02 \x01(\t*J\n\x15TemporalParsingStatus\x12\x10\n\x0cUNRECOGNIZED\x10\x00\x12\r\n\tSUCCEEDED\x10\x01\x12\x10\n\x0cSERVER_ERROR\x10\x02\x32M\n\x0fTemporalParsing\x12:\n\x05Parse\x12\x17.TemporalParsingRequest\x1a\x18.TemporalParsingResponseb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'temporal_parsing_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TEMPORALPARSINGSTATUS._serialized_start=169
  _TEMPORALPARSINGSTATUS._serialized_end=243
  _TEMPORALPARSINGREQUEST._serialized_start=26
  _TEMPORALPARSINGREQUEST._serialized_end=84
  _TEMPORALPARSINGRESPONSE._serialized_start=86
  _TEMPORALPARSINGRESPONSE._serialized_end=167
  _TEMPORALPARSING._serialized_start=245
  _TEMPORALPARSING._serialized_end=322
# @@protoc_insertion_point(module_scope)
